server:
  port: 3344
  
spring:
  application:
    name: microservice-springcloud-server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1iqueen/microservice-springcloud-server-config.git